/*
    keymap - SUN to USB scan codes table
    Copyright (c) 2017, Alexander Vollschwitz

    This file is part of suniversal.

    suniversal is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    suniversal is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with suniversal. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef SUN_TO_USB_h
#define SUN_TO_USB_h

#include "config.h"
#include "usb_codes.h"
#include "macros.h"

#if USE_MACROS == true
#define CODE_OR_MACRO(C, M) (0xFF00 + (M))
#else
#define CODE_OR_MACRO(C, M) (C)
#endif

/*
    scan code lookup table:

     - index is SUN scan code

     - value at index is USB scan code, modifier, or macro ID, as 16 bit
       unsigned int, according to this scheme:

        - non-modifiers are stored on low byte, with high byte 0
        - modifiers are stored in high byte, with low byte 0
        - 0xFF in high byte indicates that a macro is to be used, low
          byte in this case is the ID of the macro

    The scan codes are according to the keyboard documentation. Note that
    while the documentation lists two scan sets - US and International -
    we really just need one table here. As the documentation states, the
    scan sets are about key-switch to scan code assignments, but we're
    concerned with translating scan codes. From all I can tell, those are
    the same in each of the two scan sets.

    Translations were set to the same USB scan codes that a SUN Type 7
    keyboard sends.
 */
static const uint16_t sun2usb[256] = {
/*  scan                                        */
/*  code    meaning          translation to USB */
/*  --------------------------------------------*/
/* B  0x00                    */  0,
/* B 0x01    Stop            */  USB_F9,
/* B 0x02    Volume_Decr     */  0,
/* B 0x03    Again           */  USB_F5,
/* B 0x04    Volume_Incr     */  USB_F3,
/* B 0x05    F1              */  USB_F1,
/* B 0x06    F2              */  USB_F2,
/* B 0x07    F10             */  USB_F12,
/* B 0x08    F3              */  0,
/* B 0x09    F11             */  USB_F10,
/* B 0x0A    F4              */  USB_F8,
/* B 0x0B    F12             */  USB_F6,
/* B 0x0C    F5              */  USB_F4,
/* B 0x0D    GraphAlt        */  USB_TAB,
/* B 0x0E    F6              */  USB_GRAVE,
/* B 0x0F                    */  0,
/* B 0x10    F7              */  0,
/* B 0x11    F8              */  USB_MOD_LALT << 8,
/* B 0x12    F9              */  USB_MOD_LSHIFT << 8,
/* B 0x13    Alt_L           */  0,
/* B 0x14    T5_Up           */  USB_MOD_LCTRL << 8,
/* B 0x15    Pause           */  USB_Q,
/* B 0x16    Pr_Sc           */  USB_1,
/* B 0x17    Break/ScrollLock*/  0,
/* B 0x18    T5_Left         */  0,
/* B 0x19    Props           */  0,
/* B 0x1A    Undo            */  USB_Z,
/* B 0x1B    T5_Down         */  USB_S,
/* B 0x1C    T5_Right        */  USB_A,
/* B 0x1D    Esc             */  USB_W,
/* B 0x1E    1_!             */  USB_2,
/* B 0x1F    2_@             */  0,
/* B 0x20    3_#             */  0,
/* B 0x21    4_$             */  USB_C,
/* B 0x22    5_%             */  USB_X,
/* B 0x23    6_^             */  USB_D,
/* B 0x24    7_&             */  USB_E,
/* B 0x25    8_*             */  USB_4,
/* B 0x26    9_(             */  USB_3,
/* B 0x27    0_)             */  0,
/* B 0x28    -__             */  0,
/* B 0x29    =_+             */  USB_SPACE,
/* B 0x2A    ‘_~             */  USB_V,
/* B 0x2B    Backspace       */  USB_F,
/* B 0x2C    T5_Insert       */  USB_T,
/* B 0x2D    =               */  USB_R,
/* B 0x2E    /               */  USB_5,
/* B 0x2F    *               */  0,
/* B 0x30    Power           */  0,
/* B 0x31    Front           */  USB_N,
/* B 0x32    Del_.           */  USB_B,
/* B 0x33    Copy            */  USB_H,
/* B 0x34    T5_Home         */  USB_G,
/* B 0x35    Tab             */  USB_Y,
/* B 0x36    Q               */  USB_6,
/* B 0x37    W               */  0,
/* B 0x38    E               */  USB_F11,
/* B 0x39    R               */  0,
/* B 0x3A    T               */  USB_M,
/* B 0x3B    Y               */  USB_J,
/* B 0x3C    U               */  USB_U,
/* B 0x3D    I               */  USB_7,
/* B 0x3E    O               */  USB_8,
/* B 0x3F    P               */  0,
/* B 0x40    [_{             */  USB_LEFTMETA,
/* B 0x41    ]_}             */  USB_COMMA,
/* B 0x42    Delete          */  USB_K,
/* B 0x43    Compose         */  USB_I,
/* B 0x44    Home_7          */  USB_O,
/* B 0x45    up-cur_8        */  USB_0,
/* B 0x46    PgUp_9          */  USB_9,
/* B 0x47    -               */  0,
/* B 0x48    Open            */  USB_RIGHTMETA,
/* B 0x49    Paste           */  USB_DOT,
/* B 0x4A    T5_End          */  USB_SLASH,
/* B 0x4B                    */  USB_L,
/* B 0x4C    Ctrl_L          */  USB_SEMICOLON,
/* B 0x4D    A               */  USB_P,
/* B 0x4E    S               */  USB_MINUS,
/* B 0x4F    D               */  0,
/* B 0x50    F               */  USB_MUTE,
/* B 0x51    G               */  USB_VOLUMEDOWN,
/* B 0x52    H               */  USB_APOSTROPHE,
/* B 0x53    J               */  0,
/* B 0x54    K               */  USB_LEFTBRACE,
/* B 0x55    L               */  USB_EQUAL,
/* B 0x56    ;_:             */  0,
/* B 0x57    ‘_“             */  0,
/* B 0x58    \               */  USB_CAPSLOCK,
/* B 0x59    Return          */  USB_MOD_RSHIFT << 8,
/* B 0x5A    Enter           */  USB_ENTER,
/* B 0x5B    Left-Cur_4      */  USB_RIGHTBRACE,
/* B 0x5C    5               */  0,
/* B 0x5D    Right-Cur_6     */  USB_BACKSLASH,
/* B 0x5E    Ins_0           */  0,
/* B 0x5F    Find            */  USB_POWER,
/* B 0x60    T5_PgUp         */  0,
/* B 0x61    Cut             */  0,
/* B 0x62    Num_Lock        */  0,
/* B 0x63    Shift_L         */  0,
/* B 0x64    Z               */  0,
/* B 0x65    X               */  0,
/* B 0x66    C               */  USB_BACKSPACE,
/* B 0x67    V               */  0,
/* B 0x68    B               */  USB_VOLUMEUP,
/* B 0x69    N               */  USB_KP1,
/* B 0x6A    M               */  0,
/* B 0x6B    ,_<             */  USB_KP4,
/* B 0x6C    ._>             */  USB_KP7,
/* B 0x6D    /_?             */  0,
/* B 0x6E    Shift_R         */  0,
/* B 0x6F    Line_Feed       */  0,
/* B 0x70    End_1           */  USB_KP0,
/* B 0x71    Dn-Cur_2        */  0,
/* B 0x72    PgDn_3          */  USB_KP2,
/* B 0x73                    */  USB_KP5,
/* B 0x74                    */  USB_KP6,
/* B 0x75                    */  USB_KP8,
/* B 0x76    Help            */  USB_ESC,
/* B 0x77    CapsLock        */  USB_NUMLOCK,
/* B 0x78    L-Triangle      */  0,
/* B 0x79    SpaceBar        */  0,
/* B 0x7A    R-triangle      */  USB_KP3,
/* B 0x7B    T5_PgDn         */  0,
/* B 0x7C    <_>_|           */  0,
/* B 0x7D    +               */  USB_KP9,
/* B 0x7E                    */  0,
/* B 0x7F                    */  0,
/* B 0x80                    */  0,
/* B 0x81                    */  0,
/* B 0x82                    */  0,
/* B 0x83                    */  USB_F7,
/* B 0x84                    */  0,
/* B 0x85                    */  0,
/* B 0x86                    */  0,
/* B 0x87                    */  0,
/* B 0x88                    */  0,
/* B 0x89                    */  USB_END,
/* B 0x8a                    */  0,
/* B 0x8b                    */  USB_LEFT,
/* B 0x8c                    */  USB_HOME,
/* B 0x8d                    */  0,
/* B 0x8e                    */  0,
/* B 0x8f                    */  0,
/* B 0x90                    */  USB_INSERT,
/* B 0x91                    */  USB_DELETE,
/* B 0x92                    */  USB_DOWN,
/* B 0x93                    */  0,
/* B 0x94                    */  USB_RIGHT,
/* B 0x95                    */  USB_UP,
/* B 0x96                    */  0,
/* B 0x97                    */  0,
/* B 0x98                    */  0,
/* B 0x99                    */  0,
/* B 0x9a                    */  USB_PAGEDOWN,
/* B 0x9b                    */  0,
/* B 0x9c                    */  0,
/* B 0x9d                    */  USB_PAGEUP,
/* B 0x9e                    */  0,
/* B 0x9f                    */  0,
/* B 0xa0                    */  0,
/* B 0xa1                    */  0,
/* B 0xa2                    */  0,
/* B 0xa3                    */  0,
/* B 0xa4                    */  0,
/* B 0xa5                    */  0,
/* B 0xa6                    */  0,
/* B 0xa7                    */  0,
/* B 0xa8                    */  0,
/* B 0xa9                    */  0,
/* B 0xaa                    */  0,
/* B 0xab                    */  0,
/* B 0xac                    */  0,
/* B 0xad                    */  0,
/* B 0xae                    */  0,
/* B 0xaf                    */  0,
/* B 0xb0                    */  0,
/* B 0xb1                    */  0,
/* B 0xb2                    */  0,
/* B 0xb3                    */  0,
/* B 0xb4                    */  0,
/* B 0xb5                    */  0,
/* B 0xb6                    */  0,
/* B 0xb7                    */  0,
/* B 0xb8                    */  0,
/* B 0xb9                    */  0,
/* B 0xba                    */  0,
/* B 0xbb                    */  0,
/* B 0xbc                    */  0,
/* B 0xbd                    */  0,
/* B 0xbe                    */  0,
/* B 0xbf                    */  0,
/* B 0xc0                    */  0,
/* B 0xc1                    */  0,
/* B 0xc2                    */  0,
/* B 0xc3                    */  0,
/* B 0xc4                    */  0,
/* B 0xc5                    */  0,
/* B 0xc6                    */  0,
/* B 0xc7                    */  0,
/* B 0xc8                    */  0,
/* B 0xc9                    */  0,
/* B 0xca                    */  0,
/* B 0xcb                    */  0,
/* B 0xcc                    */  0,
/* B 0xcd                    */  0,
/* B 0xce                    */  0,
/* B 0xcf                    */  0,
/* B 0xd0                    */  0,
/* B 0xd1                    */  0,
/* B 0xd2                    */  0,
/* B 0xd3                    */  0,
/* B 0xd4                    */  0,
/* B 0xd5                    */  0,
/* B 0xd6                    */  0,
/* B 0xd7                    */  0,
/* B 0xd8                    */  0,
/* B 0xd9                    */  0,
/* B 0xda                    */  0,
/* B 0xdb                    */  0,
/* B 0xdc                    */  0,
/* B 0xdd                    */  0,
/* B 0xde                    */  0,
/* B 0xdf                    */  0,
/* B 0xe0                    */  0,
/* B 0xe1                    */  0,
/* B 0xe2                    */  0,
/* B 0xe3                    */  0,
/* B 0xe4                    */  0,
/* B 0xe5                    */  0,
/* B 0xe6                    */  0,
/* B 0xe7                    */  0,
/* B 0xe8                    */  0,
/* B 0xe9                    */  0,
/* B 0xea                    */  0,
/* B 0xeb                    */  0,
/* B 0xec                    */  0,
/* B 0xed                    */  0,
/* B 0xee                    */  0,
/* B 0xef                    */  0,
/* B 0xf0                    */  0,
/* B 0xf1                    */  0,
/* B 0xf2                    */  0,
/* B 0xf3                    */  0,
/* B 0xf4                    */  USB_MOD_RALT << 8,
/* B 0xf5                    */  0,
/* B 0xf6                    */  0,
/* B 0xf7                    */  0,
/* B 0xf8                    */  0,
/* B 0xf9                    */  0,
/* B 0xfa                    */  0,
/* B 0xfb                    */  0,
/* B 0xfc                    */  0,
/* B 0xfd                    */  0,
/* B 0xfe                    */  0,
/* B 0xff                    */  0,
};

#endif
